# Generated by Django 5.2.8 on 2025-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_updated_at_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID чата Telegram для уведомлений'),
        ),
    ]
